-- Add Procurement, Sales, and Accounts user roles
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PROCUREMENT';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SALES';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ACCOUNTS';
