import { Role } from "@/lib/generated/prisma/client";
import { ALL_PERMISSIONS, type Permission } from "@/lib/permissions/types";
import {
  FULL_REPORTS_DEFAULTS,
  SUPPLIERS_FULL_DEFAULTS,
  SUPPLIERS_READ_DEFAULTS,
} from "@/lib/permissions/report-permissions";

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,

  ADMIN: [
    "dashboard:view",
    "dashboard:analytics",
    "branches:view",
    "branches:create",
    "branches:edit",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:transfer",
    "inventory:reconcile",
    "menu:view",
    "menu:create",
    "menu:edit",
    "categories:view",
    "categories:manage",
    "staff:view",
    "staff:create",
    "staff:edit",
    "staff:schedules",
    "transactions:view",
    "transactions:create",
    "transactions:void",
    "transactions:manual",
    "sales:view",
    "sales:analytics",
    ...FULL_REPORTS_DEFAULTS,
    "alerts:view",
    "alerts:manage",
    "targets:view",
    "targets:create",
    "targets:edit",
    "users:view",
    "users:create",
    "users:edit",
    "settings:view",
    "settings:edit",
    "api-keys:view",
    "api-keys:manage",
    "pos:access",
    "kitchen:access",
    "orders:view",
    "orders:create",
    "orders:edit",
    "orders:assign",
    "orders:cancel",
    "warehouse:view",
    "warehouse:create",
    "warehouse:edit",
    "warehouse:transfer",
    "warehouse:approve_dispatch",
    ...SUPPLIERS_FULL_DEFAULTS,
    "commissary:view",
    "commissary:production",
    "commissary:request_dispatch",
    "transactions:purge",
    "customers:view",
    "customers:create",
    "customers:edit",
    "delivery:view",
    "delivery:manage",
    "subscriptions:view",
    "organization:view",
    "organization:edit",
    "tables:view",
    "tables:manage",
    "tables:assign",
  ],

  EXECUTIVE: [
    "dashboard:view",
    "dashboard:analytics",
    "branches:view",
    "branches:create",
    "branches:edit",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:transfer",
    "inventory:reconcile",
    "menu:view",
    "menu:create",
    "menu:edit",
    "categories:view",
    "categories:manage",
    "staff:view",
    "staff:create",
    "staff:edit",
    "staff:schedules",
    "transactions:view",
    "transactions:create",
    "transactions:void",
    "transactions:manual",
    "sales:view",
    "sales:analytics",
    ...FULL_REPORTS_DEFAULTS,
    "alerts:view",
    "alerts:manage",
    "targets:view",
    "targets:create",
    "targets:edit",
    "users:view",
    "users:create",
    "users:edit",
    "settings:view",
    "settings:edit",
    "api-keys:view",
    "api-keys:manage",
    "pos:access",
    "kitchen:access",
    "orders:view",
    "orders:create",
    "orders:edit",
    "orders:assign",
    "orders:cancel",
    "warehouse:view",
    "warehouse:create",
    "warehouse:edit",
    "warehouse:transfer",
    ...SUPPLIERS_FULL_DEFAULTS,
    "customers:view",
    "customers:create",
    "customers:edit",
    "delivery:view",
    "delivery:manage",
    "subscriptions:view",
    "organization:view",
    "organization:edit",
    "tables:view",
    "tables:manage",
    "tables:assign",
  ],

  OPERATIONS_MANAGER: [
    "dashboard:view",
    "dashboard:analytics",
    "branches:view",
    "branches:create",
    "branches:edit",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:transfer",
    "inventory:reconcile",
    "menu:view",
    "menu:create",
    "menu:edit",
    "categories:view",
    "categories:manage",
    "staff:view",
    "staff:create",
    "staff:edit",
    "staff:schedules",
    "transactions:view",
    "transactions:create",
    "transactions:void",
    "transactions:manual",
    "sales:view",
    "sales:analytics",
    ...FULL_REPORTS_DEFAULTS,
    "alerts:view",
    "alerts:manage",
    "targets:view",
    "targets:create",
    "targets:edit",
    "pos:access",
    "kitchen:access",
    "orders:view",
    "orders:create",
    "orders:edit",
    "orders:assign",
    "orders:cancel",
    "warehouse:view",
    "warehouse:create",
    "warehouse:edit",
    "warehouse:transfer",
    ...SUPPLIERS_FULL_DEFAULTS,
    "customers:view",
    "customers:create",
    "customers:edit",
    "delivery:view",
    "delivery:manage",
    "organization:view",
    "tables:view",
    "tables:manage",
    "tables:assign",
  ],

  BRANCH_MANAGER: [
    "dashboard:view",
    "dashboard:analytics",
    "branches:view",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:transfer",
    "inventory:reconcile",
    "menu:view",
    "categories:view",
    "staff:view",
    "staff:create",
    "staff:edit",
    "staff:schedules",
    "transactions:view",
    "transactions:create",
    "transactions:void",
    "transactions:manual",
    "sales:view",
    "sales:analytics",
    ...FULL_REPORTS_DEFAULTS,
    "alerts:view",
    "targets:view",
    "settings:view",
    "pos:access",
    "kitchen:access",
    "orders:view",
    "orders:create",
    "orders:edit",
    "orders:assign",
    "customers:view",
    "customers:create",
    "customers:edit",
    "delivery:view",
    "tables:view",
    "tables:manage",
    "tables:assign",
  ],

  SUPERVISOR: [
    "dashboard:view",
    "branches:view",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:reconcile",
    "menu:view",
    "categories:view",
    "staff:view",
    "staff:schedules",
    "transactions:view",
    "transactions:create",
    "transactions:manual",
    "sales:view",
    "alerts:view",
    "pos:access",
    "kitchen:access",
    "orders:view",
    "orders:create",
    "orders:edit",
    "customers:view",
    "delivery:view",
    "tables:view",
    "tables:assign",
  ],

  WAITER: [
    "dashboard:view",
    "pos:access",
    "orders:view",
    "orders:create",
    "orders:edit",
    "tables:view",
    "tables:assign",
    "customers:view",
  ],

  STAFF: [
    "dashboard:view",
    "pos:access",
    "kitchen:access",
    "orders:view",
    "orders:create",
    "orders:edit",
    "orders:assign",
    "orders:cancel",
    "transactions:view",
    "transactions:create",
    "customers:view",
    "customers:create",
    "customers:edit",
    "tables:view",
  ],

  KITCHEN_STAFF: ["kitchen:access", "orders:view"],

  AUDITOR: [
    "dashboard:view",
    "dashboard:analytics",
    "branches:view",
    "inventory:view",
    "transactions:view",
    "sales:view",
    "sales:analytics",
    ...FULL_REPORTS_DEFAULTS,
    "alerts:view",
    "targets:view",
    "orders:view",
    "warehouse:view",
    "customers:view",
  ],

  DEVELOPER: [
    "dashboard:view",
    "api-keys:view",
    "api-keys:manage",
    "settings:view",
  ],

  CALL_CENTER: [
    "dashboard:view",
    "pos:access",
    "orders:view",
    "orders:create",
    "orders:edit",
    "orders:assign",
    "customers:view",
    "customers:create",
    "customers:edit",
    "delivery:view",
    "delivery:manage",
  ],

  WAREHOUSE_STAFF: [
    "dashboard:view",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:transfer",
    "warehouse:view",
    "warehouse:create",
    "warehouse:edit",
    "warehouse:transfer",
    "warehouse:approve_dispatch",
    ...SUPPLIERS_READ_DEFAULTS,
  ],

  COMMISSARY_STAFF: [
    "dashboard:view",
    "commissary:view",
    "commissary:production",
    "commissary:request_dispatch",
    "warehouse:view",
    "warehouse:transfer",
  ],

  PROCUREMENT: [
    "dashboard:view",
    "inventory:view",
    "inventory:create",
    "inventory:edit",
    "inventory:transfer",
    "warehouse:view",
    "warehouse:create",
    "warehouse:edit",
    "warehouse:transfer",
    "warehouse:approve_dispatch",
    ...SUPPLIERS_FULL_DEFAULTS,
    "reports:view",
    "alerts:view",
  ],

  SALES: [
    "dashboard:view",
    "sales:view",
    "sales:analytics",
    "orders:view",
    "orders:create",
    "orders:edit",
    "customers:view",
    "customers:create",
    "customers:edit",
    "pos:access",
    "targets:view",
    "reports:view",
    "delivery:view",
  ],

  ACCOUNTS: [
    "dashboard:view",
    "dashboard:analytics",
    "transactions:view",
    "transactions:create",
    "transactions:manual",
    "sales:view",
    "sales:analytics",
    ...FULL_REPORTS_DEFAULTS,
    "orders:view",
    "customers:view",
  ],

  GENERIC: [],
};
